apiVersion: platform.diixtra.com/v1alpha1
kind: XImageHosting
metadata:
  name: lagu-wedding
  namespace: default
  labels:
    app.kubernetes.io/name: lagu-wedding
    app.kubernetes.io/managed-by: flux
spec:
  region: eu-west-2
  objectKey: programme.jpeg
  uploadPassword: ${password}
