apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: lagu-upload-password
  namespace: default
  labels:
    app.kubernetes.io/name: lagu-wedding
    app.kubernetes.io/managed-by: flux
spec:
  itemPath: "vaults/${OP_VAULT}/items/LAGU-QR Upload Password"
